### ISSUE TITLE
viewhtmlmail chokes on maildir

### ISSUE THREAD

**Issue by g2boojum** [akkana/scripts#2]
Your wonderful viewhtmlmail script chokes if mutt is using Maildir-formatted mailboxes.  The fix is straightforward.  If "fp = open(mbox)" fails because the mbox is actually a directory, then just do the following to read (and delete) the message:

```
maildir = mailbox.Maildir(mbox, factory=None)
key, msg = maildir.popitem()
```

**Comment by akkana** [comment]
This kind of fell by the wayside, but there have been some recent changes and some testing by someone who uses maildir, and it should work more solidly now.
