### ISSUE TITLE
termsize won't work with Python3

### ISSUE THREAD

**Issue by seebs** [akkana/scripts#6]
Yes, python3 has a "get_terminal_size" feature... But it relies on the exact same stty settings that are usually wrong for a serial console, as it just checks stty settings.

The premise of this script is that you suspect the stty settings of being wrong, because you're using a terminal which implicitly sets terminal size to 24x80, and you want to override that.

**Comment by akkana** [comment]
Sure enough. And the python2 code doesn't work in python3. I'll try to find a fix.

**Comment by akkana** [comment]
It should work now in both 2 and 3. If not, let me know.

**Comment by seebs** [comment]
Looks good to me, thanks! (I note that explicitly specifying "python2" in the #! line is probably unnecessary, and someone out there likely has a system with only python/python3, but it works for *me*.)

Thanks for the quick and thoughtful fix! I could have gotten it to work, but I couldn't have done it nearly this well.

**Comment by akkana** [comment]
You're welcome. And quite right, it should just say #!/usr/bin/env python
Thanks for pointing that out; it was left over from testing. Fixed now.
