### ISSUE TITLE
Can't install python-poppler-pyqt5

### ISSUE THREAD

**Issue by hrvoojex** [akkana/scripts#9]
Hi!
Could you give me an advice how to install a package 'python-poppler-qt5' in python3.65? It says: 'Failed to determine Qt version ([WinError 2] The system cannot find the file specified).' I have Qt 5.12 in Windows installed, PyQt5.11.3 and PyQt5-sip 4.19.13.

**Comment by akkana** [comment]
Sorry, I really don't know anything about Windows packages. You might have to ask whoever maintains python-poppler.
